### PR TITLE
Removed OwOs from ZA

### PR DESCRIPTION
**Pull request by KingMayro**
Not sure why it was asked to remove OwOs/UwUs from the ZA. But Plu gave me the ‘pleasure’ of doing it, so here's the changes.

### CODE REVIEW

**Comment by sudofox** [comment]
nature is healing

**Comment by sudofox** [comment]
```
msgid "FLIPNOTE_TITLE_FORMAT"
msgstr "flippynote  by %s"

msgid "HEADER_DETAILS"
msgstr "Derails
```

two spaces after flippynote on string 1 (should be only 1) + missing quote at the end of the second msgstr

**Comment by sudofox** [comment]
lgtm

**Comment by KingMayro** [comment]
Fixed.

**Pull request merged**
