### PR TITLE
German translation 'invalid link token' mesage tweak; minor edits

### PR DESCRIPTION
**Pull request by jojoispresent**
translated the missing string and removed some superfluous spaces

### CODE REVIEW

**Comment by jojoispresent** [comment]
no idea why it decided to take all of my edits at once..

**Comment by sudofox** [comment]
Looks like we have a merge conflict, which I can resolve pretty easily, But just to confirm:

For MUSICMATCH_RESULT_HEADER_LT_MAX and MUSICMATCH_RESULT_HEADER_GT_MAX

```
msgid "MUSICMATCH_RESULT_HEADER_GT_MAX"
msgstr "Top %d results:"

msgid "MUSICMATCH_RESULT_HEADER_LT_MAX"
msgstr "%d result(s):"
```

These would be printed as

(For when we have more than x number of results, where x is the maximum I set on the server):

`Top 5 results:`

(For when we have less than x number of results):

`3 result(s):`

* * *

Is what you have there accurate?

**Comment by jojoispresent** [comment]
image
sorry for te late reply! i have this
does the conflict mean that those 2 strings should not be edited?

**Comment by sudofox** [comment]
No, it usually just means that the copy you were working on differed somehow from the one you're trying to merge into during the time that you worked on it. All we have to do is edit it so that the correct ones are there.

However, I'd just like to clarify that we don't display the search terms in that string, only the number of songs being shown to the user.

So "Top 5 Results" becomes "Top-Resultate für 5" and so on.

Is that correct? If not, can you update it?

**Comment by jojoispresent** [comment]
ok! what i submitted just now should print out as
`Die 5 besten Resultate:` / `3 Resultate:` respectively and should be correct this way!

**Comment by sudofox** [comment]
LGTM.

**Pull request merged**
