### PR TITLE
Translate Sudomemo to Dutch

### PR DESCRIPTION
**Pull request by olafher**
Hello there!

I have translated the entire Sudomemo to Dutch (nl_NL).
There isn't much to say about it, so I hope everything is correct!

Just let me know if I need to change something.

### CODE REVIEW

**Comment by sudofox** [comment]
holy MOLY that was fast. I'll need a bit of time to review this a bit later today :)

In the meantime, feel free to attach your Flipnote Studio ID!

**Comment by olafher** [comment]
Ok! Just let me know.

FSID: 9CD45AF051002E9A

**Comment by sudofox** [comment]
@olafher I recently added some new messages to login.po. Would you be able to add those ones as well first?

**Comment by olafher** [comment]
Eummm yes I am, but not this weekend. Is it allright if I do it somewhere on Monday?

**Comment by olafher** [comment]
Correction: I did have time, so I just did it.

**Comment by sudofox** [comment]
Thank you!

The language selector is not yet implemented (I need to do that soon!) but I will set your language to Dutch.

**Comment by olafher** [comment]
Thank you!

I'll keep an eye open for mistakes on the translation and open an PR after I have corrected one of them.

**Comment by olafher** [comment]
Oh and by the way:

* Thanks for the citizenship
* If you need help with anything, I would love to do it :+1:

**Pull request merged**
