### PR TITLE
Added full Spanish translations and updated a few ones.

### PR DESCRIPTION
**Pull request by DavidTG9**
Fully added Spanish on 404.po, items.po, supportToken.po and support token options of creatorsRoom.po.

Minor fixes on blockSettings.po, browseChannel.po, channelCategories.po, colorPicker.po, inbox.po and localeSelection that improves readability by adding a more familiar language. Well I mean... you'll be the judges of that.

Also corrected some characters that were caps and when possible, reduced string length.

To avoid confusion, FLIPNOTE_FRIENDS button in the Spanish version of FS is "Erase friends" instead of "Amigos de Flipnote Studio".

To mention that some translations may be slightly different in meaning (not literal translation even when acceptable) and with a longer string, as sacrifice for more understandable and simple sentences.

If you find an error or if you need anything, reach out to me.

My FSID: 91D6 6E30 5143 095D

### CODE REVIEW

**Comment by sudofox** [comment]
> To avoid confusion, FLIPNOTE_FRIENDS button in the Spanish version of FS is "Erase friends" instead of "Amigos de Flipnote Studio".

Wat?

**Comment by DavidTG9** [comment]
When the system language is English, the button is "Flipnote Friends".
In Spanish, the button is "Borrar amigos" which translates to "Erase friends".

**Comment by DavidTG9** [comment]
> > To avoid confusion, FLIPNOTE_FRIENDS button in the Spanish version of FS is "Erase friends" instead of "Amigos de Flipnote Studio".
> 
> Wat?

When the system language is English, the button is "Flipnote Friends".
In Spanish, the button is "Borrar amigos" which translates to "Erase friends".

**Comment by meemo** [comment]
Page 4/4 of the settings in Flipnote Studio with the system language set to Spanish says:

> Copia de respaldo
> Borrar datos
> Amigos Flipnote
> Notes de muestra

**Comment by DavidTG9** [comment]
> Page 4/4 of the settings in Flipnote Studio with the system language set to Spanish says:
> 
> > Copia de respaldo
> > Borrar datos
> > Amigos Flipnote
> > Notes de muestra



Then it seems like that Spanish version is from an american DSi. Mine is from Europe. That has to be the only explanation.

**Comment by meemo** [comment]
I'm going to guess some wires got crossed during the hectic development of Flipnote Studio resulting in this. The es_MX translators may have been translating from the already translated en_US, and es_ES team might have been translating directly from the original Japanese strings.

Either way, we are not going to use "Borrar amigos" for "Flipnote Friends" since that's not what the string is used for in Sudomemo. Removing friends is only something you can do in the Flipnote Studio settings.

**Comment by sudofox** [comment]
When I wrote this translator's note, I was unaware of the different translations in the regional variant of Flipnote that you have. As such, it should be disregarded in this case. Perhaps the top screen image on that page can be referenced instead? I do believe it has text as well

**Comment by meemo** [comment]
The top screen has the same string, I tested it.

**Comment by DavidTG9** [comment]
Then I'll change it to "Amigos de Flipnote Studio" or just "Amigos de FS" or "Amigos de Flipnote" if the first string is too long and shows incorrectly on the page or something.

**Comment by sudofox** [comment]
What's it use in the Americas Spanish version?

**Comment by meemo** [comment]
It uses "Amigos Flipnote" (which is what we would prefer).

**Comment by sudofox** [comment]
Okay, then we're going to use that.

**Pull request merged**
