### PR TITLE
added Swedish translation

### PR DESCRIPTION
**Pull request by sweirde**
Flipnote ID: 90EFFDC05118CDB1
(I'm coming back to Sudomemo soon, I need to enable my new internet connection to connect to the DSi...)

Note: I kept the "stars" name in English as it's more simple to understand and there is no translation to "starred flipnotes". I hope that's ok!
If the å ä ö letters don't show up in the .po file, let me know!

### CODE REVIEW

**Comment by sudofox** [comment]
Going to review today, thank you!

**Comment by sudofox** [comment]
Looks good! The accents do appear to have the correct encoding as well.

**Comment by sudofox** [comment]
@sweirde I missed a few things with my validation: a few entries had double quotes in them that were not escaped:

`\"`

or replaced by single quotes:

`'`

I also noticed some entries that did not have the opening double quote in them.

I will run my validation script before approving in the future, I should've caught it immediately.

Finally, regarding the special characters - I found that your entries seemed to be in the wrong text encoding: ISO-8859-1, rather than UTF-8. I'm not convinced that this is even your fault -- it may be a setting for my repository that I need to adjust. Did you use the GitHub website or your own editor?

* * *

Either way, this is an excellent addition, thank you very very much!

**Comment by sweirde** [comment]
If I had known these mistakes, I'd be sure to let you know. So sorry!
Regarding what editor I used, I wrote everything in Notes, is there any way you know that can fix the encoding? I don't know any of that myself, but if help is needed getting the letters I'm up for it.
Otherwise, I'm glad to have helped! When do you think I'll be able to test it?

**Pull request merged**
