### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by knuxify**
Current status: The base translation is done, although it's a little rough around the edges. It can be merged without changes, but it would be nice if somebody could double-check it beforehand.

## Caveats

- In a lot of cases, the user is referred to by male gendered words (``wysłał``, ``wysłałeś``). This could be mitigated in two ways:
  * changing the words to "add" the female endings (for example ``wysłał(a)`` or ``wysłałeś/aś``)
  * changing the words to use ``strona bierna`` (for example ``wysłano``)
- ``Flipnotes`` is not translated, and instead used directly (for example ``Pokaż Flipnotes``). In my opinion, ``Flipnotey``, ``Flipnote-y`` or ``Flipnoty`` as alternatives feel a bit off.

### CODE REVIEW

**Comment by sudofox** [comment]
Hey @knuxify! I'll need a little while to review this and let you know if there's anything that needs updating. Thank you for the details on the nuances and nature of the Polish language, it's quite helpful.

**Comment by sudofox** [comment]
```
[aburk@aburk-laptop sudomemo-locales]$ ./po2mo.sh > /dev/null 
./pl_PL/LC_MESSAGES/sudomemoPlus.po:19: end-of-line within string
msgfmt: found 1 fatal error
./pl_PL/LC_MESSAGES/detailsPage.po:24: end-of-line within string
msgfmt: found 1 fatal error
```

Hey, looks like we have some unterminated strings here. Would you be able to resolve those?

Additionally, I'm about to make the following additions to all the rest; I wanted to wait until I was able to review yours but I'm kinda running out of time for these changes. Could you add these in while you're at it?

```
## profilePicture.po

msgid "LOGIN_REQUIRED_TO_CHANGE"
msgstr "You must be logged in to change your profile picture."

## reportContent.po

msgid "THANKS_FOR_REPORTING"
msgstr "We've received your report. Thanks for helping make Sudomemo a better place!"

## creatorsRoom.po

msgid "LOGIN_REQUIRED_ACTION"
msgstr "You must be logged in to perform this action."

msgid "PAGE"
msgstr "Page"

msgid "PAGE_COUNTER_FORMAT"
msgstr "%d of %d"

msgid "PREV"
msgstr "Previous"

msgid "NEXT"
msgstr "Next"

## tickets.po

msgid "DONT_HAVE_ANY_TO_USE"
msgstr "You don't have any of that item to use."

## themeShop.po

msgid "THEME_SHOP"
msgstr "Theme Shop"
```

**Comment by knuxify** [comment]
@sudofox done!

**Comment by sudofox** [comment]
Thanks! I'll merge it in now and do a bit of testing before making it live.

**Pull request merged**
