### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by Jean20B**
Flipnote Studio ID : 93D2B9B059AD4FF7
I don't know if accents work 🤔

### CODE REVIEW

**Comment by sudofox** [comment]
You've got something funky going on with the text encoding there. I'll need some time to look through it.

No worries, just gotta make sure it's all good.

**Comment by sudofox** [comment]
@Jean20B Sorry, but something is kinda goofed with your files' encoding. But don't worry!

Please:

- make sure you save your files in UTF-8 encoding (depending on which editor you're using, it will be in a different spot. Your files seem to be a somewhat odd amalgam ISO-8859-1 and something else.
- you might try updating the files with the GitHub web editor; at least then whatever encoding they are, it will be consistent and I can fix them up myself.

**Comment by Jean20B** [comment]
Is it good ? (blockSettings)

**Comment by sudofox** [comment]
@Jean20B Yes, blockSettings looks to have the correct characters and correct (UTF-8) encoding as well now.

**Comment by sudofox** [comment]
Passed .po validation.

Accepting PR, thanks

**Pull request merged**
