### PR TITLE
tr_TR Initial translation

### PR DESCRIPTION
**Pull request by KingKnight12**

### CODE REVIEW

**Comment by meemo** [comment]
Looks good, however I'm going to hold off on merging for now until more files are translated since tr_TR is so new.

**Comment by KingKnight12** [comment]
> Looks good, however I'm going to hold off on merging for now until more files are translated since tr_TR is so new.

ok

**Comment by meemo** [comment]
Are you in the translator discord server yet? If not, join the [Sudomemo Discord](https://flipnot.es/discord) and send SudoModMail a DM.

**Comment by KingKnight12** [comment]
> Are you in the translator discord server yet? If not, join the [Sudomemo Discord](https://flipnot.es/discord) and send SudoModMail a DM.

I'm already on the server since 2020

**Pull request merged**
