### PR TITLE
Fixed german translation

### PR DESCRIPTION
**Pull request by TrashMe5951**
I edited almost every file. The translations I fixed were mostly already correct before, but a native speaker just wouldn't speak like that, because some translations sounded a little weird, so I fixed it. Btw I'm a native speaker myself.

My Flipnote Studio ID is 9EDBBA100717D25E

### CODE REVIEW

**Comment by sudofox** [comment]
Hi! I'm reviewing now. Good news: there's no syntax errors, so once I finish checking it over we should be able to merge it in.

Do you have a Twitter?

**Comment by TrashMe5951** [comment]
> Hi! I'm reviewing now. Good news: there's no syntax errors, so once I finish checking it over we should be able to merge it in.
> 
> 
> 
> Do you have a Twitter?

Yeah, I have Twitter: @TrashMe__ :)

**Comment by sudofox** [comment]
Alright, so I've found a few issues. Most should be pretty quick to fix; one of the primary things however is that Creator's Room needs to keep the concept of it being an actual "room", as in a place that you can visit.

In the page counter text for some of these, you've added Seite into them - which would be fine, except that Seite would be displayed twice in the line, for example:

```
Seite     Seite 1 von 4
```

In login.po, you've added second sentence to NEW_USER_WELCOME_FORMAT that wasn't in the original - while it is a nice thing to say, it might not display correctly in the page (I haven't checked) and if we, say, added a similar text later, yours would become duplicate.

In login.po, EMAIL_VERIFICATION_ADDRESS_REMOVED is still untranslated.

In the mail messages about content removal/restoration, CONTENT_TYPE_room_theme should always specify that it's a Creator's Room Theme.

When talking about Creator's Rooms, words referring to page or profile won't work because the idea of a Creator's Room is specifically tied to actual rooms. We're even prototyping a sort of room that you can decorate as a fun mini-game, so we need to keep that concept in the naming. 

Under reportContent, the new translation for REPORT_FAILED_USER_BANNED might be too long as it shows up in an error message which do not wrap to the next line. Can you try to shorten it?

Under tickets, TICKET_DESC_purple_bunny_ticket doesn't seem to be translated

Under trophies, ACHIEVEMENT_EARNED should be left as Achievement Get! as it's meant as a pop-culture reference. I should have put a note in there about it, I'll add that later. Sorry about that!

**Comment by TrashMe5951** [comment]
> Alright, so I've found a few issues. Most should be pretty quick to fix; one of the primary things however is that Creator's Room needs to keep the concept of it being an actual "room", as in a place that you can visit.
> 
> 
> 
> In the page counter text for some of these, you've added Seite into them - which would be fine, except that Seite would be displayed twice in the line, for example:
> 
> 
> 
> ```
> 
> Seite     Seite 1 von 4
> 
> ```
> 
> 
> 
> In login.po, you've added second sentence to NEW_USER_WELCOME_FORMAT that wasn't in the original - while it is a nice thing to say, it might not display correctly in the page (I haven't checked) and if we, say, added a similar text later, yours would become duplicate.
> 
> 
> 
> In login.po, EMAIL_VERIFICATION_ADDRESS_REMOVED is still untranslated.
> 
> 
> 
> In the mail messages about content removal/restoration, CONTENT_TYPE_room_theme should always specify that it's a Creator's Room Theme.
> 
> 
> 
> When talking about Creator's Rooms, words referring to page or profile won't work because the idea of a Creator's Room is specifically tied to actual rooms. We're even prototyping a sort of room that you can decorate as a fun mini-game, so we need to keep that concept in the naming. 
> 
> 
> 
> Under reportContent, the new translation for REPORT_FAILED_USER_BANNED might be too long as it shows up in an error message which do not wrap to the next line. Can you try to shorten it?
> 
> 
> 
> Under tickets, TICKET_DESC_purple_bunny_ticket doesn't seem to be translated
> 
> 
> 
> Under trophies, ACHIEVEMENT_EARNED should be left as Achievement Get! as it's meant as a pop-culture reference. I should have put a note in there about it, I'll add that later. Sorry about that!
> 
> 
> 
> 

That was quick :)
I'll fix these things now

**Comment by sudofox** [comment]
I realized that I wasn't seeing the entire file when reviewing, it looks like there's more untranslated strings here and there, e.g in trophies.po - I'll look it over again when you're done

**Comment by TrashMe5951** [comment]
Oh, ok. I'm done now with the mistakes you mentioned in the first comment, I'll now look over and translate the untranslated strings.

**Comment by TrashMe5951** [comment]
Ok, I'm done now.

**Comment by sudofox** [comment]
Alright, hopefully this is our last run.

- trophies.po, TROPHY_DESC_colors_promo seems to have both English and German
- theatre.po, TROPHY_CASE and UNTITLED_FLIPNOTE_BY_FORMAT are still in English
- mail_spinoff.po, you don't need to change anything here but let us know if it wraps strangely on the DS, I might have to improve the letter styling. You can get one to test by having someone spin-off your Flipnote.
- mailSettings.po, TYPE_SERVICE_UPDATE_NAME is still in English.
- followNotificationEmail.po - confirm all of these are correct in German?
- creatorsRoom.po - PAGE_COUNTER_FORMAT still has extra word

**Comment by TrashMe5951** [comment]
Thought, it was now finished, I'm sorry for my mistakes 😅
I'm gonna fix it now

**Comment by TrashMe5951** [comment]
Ok, done, I hope now everything is correct, and once again, I'm sorry for the trouble bc of my mistakes.

**Comment by sudofox** [comment]
It's no problem! There's a lot of text here and it's rare for anyone to get it the first time around.

Things look good to me. I'll be bringing it in now.

**Pull request merged**
