### PR TITLE
Update mailSettings.po

### PR DESCRIPTION
**Pull request by Bukharin1**

### CODE REVIEW

**Comment by Bukharin1** [comment]
Hello! I think that the translation is in agreement, but there is a place I do not understand.
Is "spin-off" the same as "Child Flipnote"?

**Comment by sudofox** [comment]
Yes, I believe so.
Spin-off = Derivative work

I would prefer if the original term from Ugomemo Hatena was used.

**Comment by sudofox** [comment]
I will merge this now - things look good to me.

**Comment by Bukharin1** [comment]
Okay, that's fine.!

**Pull request merged**
