### PR TITLE
updating owo lango!

### PR DESCRIPTION
**Pull request by oscie57**
hi theres alot that i missed but this makes it more up to date
i got bored after so apologies
i dont use github web so i didnt know how to replace files (which is why i deleted them all and reuploaded)

### CODE REVIEW

**Comment by oscie57** [comment]
FSID: 990394C05990C5C6

**Comment by sudofox** [comment]
Not gonna merge until I do a diff from our master to your branch because of that first commit

**Comment by sudofox** [comment]
https://github.com/Sudomemo/sudomemo-locales/pull/389/files okay I can do "changes from all commits"

I'd like you to significantly cut down on the owo and replacing of consonants with w, it should be sprinkled in but it's currently very overpowering.

**Comment by oscie57** [comment]
ah alright, i can work on that tomorrow!

**Comment by sudofox** [comment]
how're we looking?

**Comment by meemo** [comment]
Any updates?

**Comment by oscie57** [comment]
hi im sorry ive been super busy and havent had time to work on it, ill try do it whenever i can

**Comment by meemo** [comment]
Closing due to inactivity. Please open a new pull request if you can find the time to finish this.

**Pull request closed without merging**
