### PR TITLE
Added Welsh (Cymraeg) Language

### PR DESCRIPTION
**Pull request by mnmannayw**
I've added a new language to Sudomemo, Welsh! I live in Wales and love the language so I though I'd share the love and spread it to Sudomemo. Any grammar or spelling errors feel free to edit and correct. FSID: 9260EE60A0C21724 Twitter: @sirltparker76

### CODE REVIEW

**Comment by sudofox** [comment]
```
[aburk@aburk-laptop sudomemo-locales]$ ./po2mo.sh > /dev/null 
./cy_GB/LC_MESSAGES/themeShop.po:92:63: syntax error
./cy_GB/LC_MESSAGES/themeShop.po:92: keyword "Fy" unknown
msgfmt: found 2 fatal errors
```

On line 92, one of your escaped double quotes has had the \ placed after the quote instead of before.

```
./cy_GB/LC_MESSAGES/emailVerificationReminder.po:17: keyword "Angen" unknown
./cy_GB/LC_MESSAGES/emailVerificationReminder.po:17:13: syntax error
./cy_GB/LC_MESSAGES/emailVerificationReminder.po:18: end-of-line within string
msgfmt: found 3 fatal errors
```

On line 17, you are missing a leading quote.

```
./cy_GB/LC_MESSAGES/mailSettings.po:95: keyword "Os" unknown
./cy_GB/LC_MESSAGES/mailSettings.po:95:19: syntax error
./cy_GB/LC_MESSAGES/mailSettings.po:96: end-of-line within string
msgfmt: found 3 fatal errors
```

On line 95, you have an extraneous `msgstr "`

In tickets.po, one of the comments has some extra text in it, and it seems to be missing some of the latest ticket types. 

It looks like you've been working on this for a decent bit and I appreciate it! When the things mentioned above are resolved, I'll do another check on it to make sure we have everything that's needed.

**Comment by sudofox** [comment]
Thanks! I will review this soon :)

**Comment by mnmannayw** [comment]
@sudofox Are there any other errors in the files?

**Comment by Kaden745** [comment]
Hi

**Comment by Kaden745** [comment]
hola

**Comment by mnmannayw** [comment]
.............

**Comment by sudofox** [comment]
Sorry for the delay! I'll get this added in soon. Been busy in other departments

**Comment by mnmannayw** [comment]
Ok thank you

**Comment by mnmannayw** [comment]
Might do *AHOY!* Pirate English next.

**Comment by sudofox** [comment]
Okay! Everything is looking pretty good. I did add something recently to flipnoteOptions.po so you might want to add that before I finally pull it in.

One other thing: you seem to have added an Azure CI config file in this commit:

https://github.com/Sudomemo/sudomemo-locales/pull/154/commits/f9a95b47b58d8d1b92aa6a751cab31610f48113b

Can you please remove that file?

**Comment by mnmannayw** [comment]
Ok one second

**Comment by mnmannayw** [comment]
@sudofox All done!

**Comment by mnmannayw** [comment]
I am also planning on learning other languages like Scottish Gaelic and Pirate English (bit of a funny joke one like the en_XD meme one) which I might eventually add.

**Comment by mnmannayw** [comment]
Ok something weird just happened I accidentally uploaded some English ones

**Comment by mnmannayw** [comment]
I just made a folder in my fork of Sudomemo_Locales and now it's appeared on this pull request for some reason when I don't want them to. The name of the folder is "en_PT" and it shouldn't be on the pull request. You might see something recent saying "Add files via upload" or "Create blockSettings.po" which shouldn't be on the pull request.

**Comment by sudofox** [comment]
@mnmannayw I'm going to merge this in. However you may run into some UNTRANSLATED_STRINGs here and there as I've added a lot of things since then. I'll do my best to add them in in a future commit after I merge it in.

It will not become available on Sudomemo until after the release of Sudomemo Plus when I have been able to test sufficiently. However, I don't want this to get further behind so I am pulling it now.

**Comment by mnmannayw** [comment]
Ok thank you

**Pull request merged**
