### PR TITLE
Archive translation (RO)

### PR DESCRIPTION
**Pull request by Tescu48**

### CODE REVIEW

**Comment by meemo** [comment]
Looks good, we're just missing either ignores or translations for the following files:

ro_RO/LC_MESSAGES/archive.po:
CONTACT
FLIPNOTE_ARCHIVE
FLIPNOTE_STUDIO_ID
HATENA_ID
MONTH_DAY_YEAR_FORMAT
MONTH_YEAR_FORMAT
SONG_ALBUM
SPOTIFY
SUDOMEMO
YOUTUBE_MUSIC

ro_RO/LC_MESSAGES/supportToken.po:
SUPPORT_TOKEN_INFO

ro_RO/LC_MESSAGES/theatre.po:
MUSICMATCH

**Comment by Tescu48** [comment]
> Looks good, we're just missing either ignores or translations for the following files:
> 
> ro_RO/LC_MESSAGES/archive.po: CONTACT FLIPNOTE_ARCHIVE FLIPNOTE_STUDIO_ID HATENA_ID MONTH_DAY_YEAR_FORMAT MONTH_YEAR_FORMAT SONG_ALBUM SPOTIFY SUDOMEMO YOUTUBE_MUSIC
> 
> ro_RO/LC_MESSAGES/supportToken.po: SUPPORT_TOKEN_INFO
> 
> ro_RO/LC_MESSAGES/theatre.po: MUSICMATCH

Support token info string has been translated. The others are ignores as they're names (or in the case of contact and album, it's the same as in English). Month format remains the same.

**Comment by meemo** [comment]
If they should be the same they should be put ignore ignore files, i.e.:

`ignores/ro_RO/archive.txt` would contain:
```
CONTACT
FLIPNOTE_ARCHIVE
FLIPNOTE_STUDIO_ID
HATENA_ID
MONTH_DAY_YEAR_FORMAT
MONTH_YEAR_FORMAT
SONG_ALBUM
SPOTIFY
SUDOMEMO
YOUTUBE_MUSIC
```

And so on.

**Comment by Tescu48** [comment]
Yeah these are the ones.

**Comment by meemo** [comment]
So close, just missing and ignore file for this ID:

ro_RO/LC_MESSAGES/theatre.po:
MUSICMATCH

And this appears to be missing a translation:

ro_RO/LC_MESSAGES/supportToken.po:
SUPPORT_TOKEN_INFO

**Comment by Tescu48** [comment]
Added MUSICMATCH to ignores. As for SUPPORT_TOKEN_INFO, it's already done ant 8c1d846

**Comment by meemo** [comment]
Thank you very much!

**Pull request merged**
