### PR TITLE
Additional Comment to ''Added German Translations''

### PR DESCRIPTION
**Pull request by LordSkittler**
Flipnote Studio: 9FF60D00A0A81799

### CODE REVIEW

**Comment by jaames** [comment]
@sudofox make sure this is squashed before it's merged haha :P

**Comment by sudofox** [comment]
@LordSkittler I need you to make a few changes.

1. For some reason, in detailsPage you seem to have a byte-order-mark at the very first line. Please remove this - retype the line, and verify that whatever you used to edit the file does not have the encoding set to UTF-8 with BOM -- should just be UTF-8.

```
aburk@aburk:~/sudomemo-locales/de_DE$ diff detailsPage.po{,.aburk.bak}
1c1
< msgid "TIMESTAMP_FORMAT"
---
> ﻿msgid "TIMESTAMP_FORMAT"
aburk@aburk:~/sudomemo-locales/de_DE$ head -n1 detailsPage.po|xxd
00000000: 6d73 6769 6420 2254 494d 4553 5441 4d50  msgid "TIMESTAMP
00000010: 5f46 4f52 4d41 5422 0a                   _FORMAT".
aburk@aburk:~/sudomemo-locales/de_DE$ head -n1 detailsPage.po.aburk.bak|xxd
00000000: efbb bf6d 7367 6964 2022 5449 4d45 5354  ...msgid "TIMEST
00000010: 414d 505f 464f 524d 4154 220a            AMP_FORMAT".
```

2. While you worked, I added a few new strings.

To these files

```
channelDetails.po
chatrooms.po
flipnoteComments.po
```

I added the following to the end:

```
msgid "CONFIRM_EMAIL_BEFORE_POSTING"
msgstr "Please confirm your email before posting."
```

To reportContent.po, I added:

```
msgid "CONFIRM_EMAIL_BEFORE_REPORTING"
msgstr "Please confirm your email before reporting content."
```

Please add these (translated) strings and replace the first line of detailsPage.po, and it should be all good.

**Comment by sudofox** [comment]
@LordSkittler Any news?

**Comment by sudofox** [comment]
Closing as I have not heard back

**Comment by sudofox** [comment]
Sudomemo's locale text will be updated again soon, so feel free to fork, update, and submit a PR after that's happened if any changes need to be made.

**Comment by crensyhanilas** [comment]
Spelled Wrong: italian.html by hanilas

**Pull request closed without merging**
