### PR TITLE
Add ticket gifting strings for console

### PR DESCRIPTION
**Pull request by J0w03L**
Exactly what the title says

### CODE REVIEW

**Comment by Furdox** [comment]
Me when I'm translating new strings before the original strings aren't even merged

**Comment by J0w03L** [comment]
Ty!

**Comment by Furdox** [comment]
using my lte for this lmao, school blocking ssh moment
Screenshot_20240410-123607_crDroid Home

**Comment by J0w03L** [comment]
Yeah thats exactly why I setup a wireguard VPN over TCP lol

**Comment by Vickerinox** [comment]
i've translated the strings for sv_SE (swedish) do i simply commit them on this branch? I've not previously contributed to existing pull requests here.

**Comment by Furdox** [comment]
I need to setup an html proxy at one point to use my website domain to have a web ssh thing

Anyways, first pass is done, need to do some more later plus repass on them
Screenshot_20240410-125709_PortX

(don't mind me forgoring to git add lmaoo)

**Comment by Furdox** [comment]
> i've translated the strings for sv_SE (swedish) do i simply commit them on this branch? I've not previously contributed to existing pull requests here.

Personally, I'll just wait until this gets merged then make a new pull request using my existing changes.

**Comment by J0w03L** [comment]
Yeah, that's the easiest and cleanest way.

**Comment by Vickerinox** [comment]
Got it, ill stick onto them then :P

**Comment by Furdox** [comment]
:3

**Comment by Furdox** [comment]
Ready for pull request. Waiting for this pull request to be merged before reupdating my repo to latest and making another pull request.
uwu

**Pull request merged**
