### PR TITLE
[FR] translated (lgbtq+ reference!?!?!?!)

### PR DESCRIPTION
**Pull request by Furdox**
I'm tired of fr_FR, when will fr_CA become real so my Sudomemo becomes better ;w;

### CODE REVIEW

**Comment by Furdox** [comment]
it updated :insane:

**Comment by Furdox** [comment]
closing because too much stuff has happened so I'll make a new pr

**Comment by Furdox** [comment]
reopening because github is fudging epic, still a draft though (I forgot how to make prs drafts)

**Comment by Furdox** [comment]
epic, no more conflicts

**Comment by Furdox** [comment]
krill yourself

**Comment by Furdox** [comment]
will continue later I tired

**Comment by Furdox** [comment]
Finally done, this can be merged now.
ralsei_YIPPEE_confetti

**Comment by Furdox** [comment]
are you fr :insane:

**Comment by Furdox** [comment]
now updated and ready to merge again
:ralsei_eepy:

**Comment by meemo** [comment]
Thanks!

**Pull request merged**
