### PR TITLE
Various translations to spanish.

### PR DESCRIPTION
**Pull request by fixfy**
Fixed inbox.po to a more accurate spanish translation.
Fully translated spin-off notification to spanish.
Fully translated mail.po to spanish
Updated mail_spinoff.po to a more accurate spanish
Fully translated mail_content_removed.po to spanish
Updated mail_content_removed.po to fix some spanish words

FSID:5B7DF1808AC1C6A0

### CODE REVIEW

**Comment by sudofox** [comment]
Hey! I'll review this soon

**Comment by sudofox** [comment]
browseFlipnotes.po:

- CATEGORY_random untranslated
- CATEGORY_feed untranslated (?)

detailsPage.po:

- HEADER_SONG untranslated
- UNTITLED_FLIPNOTE_BY_FORMAT untranslated

emailVerificationReminder.po:

- EMAIL_VERIFICATION_REMOVE_ME untranslated

login.po:

- EMAIL_VERIFICATION_ADDRESS_REMOVED untranslated

mailSettings.po:

- TYPE_UNREAD_COMMENTS_NAME untranslated
- TYPE_UNREAD_COMMENTS_DESC untranslated
- TYPE_SERVICE_UPDATE_NAME untranslated
- TYPE_SERVICE_UPDATE_DESC untranslated


mail_content_restored.po:

- None of this is translated

mail_report_accepted.po:

- None of this is translated

mail_report_rejected.po:

- None of this is translated

menuHeaders.po:

- GET_STARTED untranslated

profilePicture.po:

- LOGIN_REQUIRED_TO_CHANGE untranslated

theatre.po:

- TROPHY_CASE untranslated
- UNTITLED_FLIPNOTE_BY_FORMAT untranslated

themeShop.po:

- THEME_SHOP untranslated

tickets.po:

- Everything after DONT_HAVE_ANY_TO_USE is still untranslated

trophies.po:

- None of this is translated

**Comment by fixfy** [comment]
I reviewed your message and I translated more files! I hope everything is ok, as I did my best to give the most accurate translation to anything on the files... muchas gracias.

**Comment by sudofox** [comment]
Thanks! Sorry for the delay, will review this soon :)

**Comment by sudofox** [comment]
@fixfy 

```
./es_ES/LC_MESSAGES/trophies.po:51: end-of-line within string
msgfmt: found 1 fatal error
./es_ES/LC_MESSAGES/mail_report_accepted.po:44: end-of-line within string
./es_ES/LC_MESSAGES/mail_report_accepted.po:44:9: syntax error
msgfmt: found 2 fatal errors
```

**Comment by fixfy** [comment]
> @fixfy
> 
> ```
> ./es_ES/LC_MESSAGES/trophies.po:51: end-of-line within string
> msgfmt: found 1 fatal error
> ./es_ES/LC_MESSAGES/mail_report_accepted.po:44: end-of-line within string
> ./es_ES/LC_MESSAGES/mail_report_accepted.po:44:9: syntax error
> msgfmt: found 2 fatal errors
> ```
what happened? is there something wrong? :s

**Comment by sudofox** [comment]
I fixed the syntax errors :) 

- in tickets.po, everything after TICKET_NAME_ffotd_ticket is still untranslated.

Can you take care of that? After that, I'll be able to accept them. Thanks so much!

**Comment by fixfy** [comment]
hi! I updated tickets.po already. If you need something more to translate lmk :)

**Comment by sudofox** [comment]
Thanks.

I did end up missing a syntax error so I just fixed it after merge time.

**Pull request merged**
