### PR TITLE
Update archive.po

### PR DESCRIPTION
**Pull request by chakojp**

### CODE REVIEW

**Comment by chakojp** [comment]
I can also translate FAQs and history pages.

**Comment by sjkim04** [comment]
Hi @chakojp, please make this into a single pull request (merge all commits to a single branch, and then submit a PR to the original repository)

**Comment by sjkim04** [comment]
@sudofox @meemo new ja_JP contributor, I think?

**Comment by sjkim04** [comment]
SudomemoのDiscordサーバーに入っていらっしゃるなら、SudoModMailに翻訳をしたい趣旨をDMで伝えると、翻訳者専用のサーバーに入れます。これからよろしくお願いします！

If you’re in the Sudomemo Discord server, DMing SudoModMail that you want to translate for Sudomemo, you’ll be able to get an invite to a translator-specific server. Nice to meet you!

**Comment by meemo** [comment]
Closed since #440 has been merged. Please submit only 1 pull request in the future.

**Pull request closed without merging**
