### PR TITLE
Fixed Dutch Translation

### PR DESCRIPTION
**Pull request by Suhbahstiejaan**
I strongly suspect the original translation to be done via machine translation, as there are mistakes in here that don't make sense for a human to make.
So I fixed the grammatical errors that resulted from the original machine translation, and added translations where there were none!

### CODE REVIEW

**Comment by sudofox** [comment]
```
./po2mo.sh > /dev/null 
./nl_NL/LC_MESSAGES/blockSettings.po:20: keyword "Geblokkeerde" unknown
./nl_NL/LC_MESSAGES/blockSettings.po:20:105: syntax error
msgfmt: found 2 fatal errors
```

Check for stray double-quotes, if you need to use them then escape them like `\"`

**Comment by SnowpMakes** [comment]
I apologize,
I did not use Google Translate to translate these, and I’m sorry for all the mistakes.
My Dutch is not the best in the world, so I’m glad you were able to fix it!

Some of your changes were really quite obvious, and I feel stupid that I made those mistakes. For example, using `themawinkel` instead of `thema winkel`. I will try to keep this pattern up if/when I make any contributions in the future.

**Comment by Suhbahstiejaan** [comment]
> Check for stray double-quotes, if you need to use them then escape them like `\"`
Ah alright! I just pushed a commit changing them to single quotes to make it more consistent with the rest of the text

**Comment by sudofox** [comment]
Hey @SnowpMakes, thanks for chiming in. No worries, we still appreciate the work you put into it :)

@Suhbahstiejaan, looks good! Thank you very much!

**Comment by Suhbahstiejaan** [comment]
> 
> 
> I apologize,
> I did not use Google Translate to translate these, and I’m sorry for all the mistakes.
> My Dutch is not the best in the world, so I’m glad you were able to fix it!
> 
> Some of your changes were really quite obvious, and I feel stupid that I made those mistakes. For example, using `themawinkel` instead of `thema winkel`. I will try to keep this pattern up if/when I make any contributions in the future.

It's totally alright! It's cool to see that people are still learning the language, and I am glad to be able to help fix the translation! I think it's awesome that some stranger like me can just dive into the source of the translation files and propose changes in this way!

**Comment by sudofox** [comment]
Still need your FSID @Suhbahstiejaan :)

**Comment by Suhbahstiejaan** [comment]
@sudofox 
Sorry! It's taking a while because I had to dig up my 3DS, connect it to the internet (the router changed) and look it up in the menu.
I'll respond with it as soon as possible!

**Comment by sudofox** [comment]
Sounds good, If you toss us a Twitter handle as well, we'll shout you out.

**Comment by Suhbahstiejaan** [comment]
Okay found it! My FSID is 91097A4065ED00EF and my Twitter is https://twitter.com/suhbahstiejaan

**Comment by sudofox** [comment]
Thanks! Log in to Sudomemo to get your special Trophy!

**Pull request merged**
