### PR TITLE
Updated new strings

### PR DESCRIPTION
**Pull request by guido-pavesi**
Added italian translations to the new strings.

### CODE REVIEW

**Comment by meemo** [comment]
Something seems off here, there are wayyy too many changes for updating a single language.

**Comment by guido-pavesi** [comment]
@meemo it is normal because I had to sync my already existing fork to make updates.

**Comment by guido-pavesi** [comment]
Also, I used the same branch of the last time I contributed.

**Comment by meemo** [comment]
This is not normal, it appears that the merges of upstream changes have screwed up the commit history here. This will take a while to cherry pick the commits that apply to it_IT, but we can accept this.

**Comment by guido-pavesi** [comment]
Ooh...then, sorry for the mess...

**Comment by meemo** [comment]
Sorry for the delay on this, we've been super busy with the archive. I'll get to this soon!

**Comment by sudofox** [comment]
@meemo when you have a second...

**Comment by sudofox** [comment]
Actually, we should probably reject PRs like this and have them rebase

**Pull request closed without merging**
