### PR TITLE
Greek Translations

### PR DESCRIPTION
**Pull request by bananatole**
I have added and edited translations up to discordbot- i will do the rest later! :)

### CODE REVIEW

**Comment by sudofox** [comment]
Cool, I'll wait for the rest before merging em in.

**Comment by bananatole** [comment]
idk if i did this correctly but ive updted up to theme shop- theres only a few left but im dead tired, ill finish it up in the morning!

**Comment by bananatole** [comment]
Everything is ready!

**Comment by sudofox** [comment]
```
./el_GR/LC_MESSAGES/youtube.po:49:52: syntax error
msgfmt: found 1 fatal error
./el_GR/LC_MESSAGES/tickets.po:200:9: syntax error
./el_GR/LC_MESSAGES/tickets.po:200: keyword "Sudomemo" unknown
./el_GR/LC_MESSAGES/tickets.po:201: end-of-line within string
msgfmt: found 3 fatal errors
./el_GR/LC_MESSAGES/login.po:157:150: syntax error
msgfmt: found 1 fatal error
```

**Comment by sudofox** [comment]
Looks like the syntax errors are resolved. We do have some untranslated strings though:


```
# sudomemo-locales Problem Finder
Scans for problems as well as untranslated (or identical) strings

## el_GR

el_GR/LC_MESSAGES/browseFlipnotes.po:
HEADER_FLIPNOTES
HEADER_ROLEPLAYS
SUDOMEMO

el_GR/LC_MESSAGES/channelCategories.po:
FANDOMS
ROLEPLAYS

el_GR/LC_MESSAGES/channelDetails.po:
FLIPNOTES

el_GR/LC_MESSAGES/chatrooms.po:
MODERATOR

el_GR/LC_MESSAGES/creatorsRoom.po:
ADMIN_ACCT_BANNED
BLOCK_COMMENTS_LINK
FLIPNOTE_STUDIO_ID
INVENTORY
PREVIEW
RANKING

el_GR/LC_MESSAGES/dailyStarReport.po:
STRING_SUDOMEMO

el_GR/LC_MESSAGES/detailsPage.po:
HEADER_FLIPNOTE_ID
HEADER_SPINOFFS

el_GR/LC_MESSAGES/discordbot.po:
MUSICMATCH_MOVIE_COUNT_PLURAL
MUSICMATCH_MOVIE_COUNT_SINGULAR
USAGE
USAGE_give_plus
USAGE_INTRO
USAGE_link
USAGE_musicmatch

el_GR/LC_MESSAGES/flipnoteOptions.po:
FLIPNOTE_URL_IS
OPTION_NAME_FORCE_44K_BITRATE
OPTION_NAME_SMOOTH

el_GR/LC_MESSAGES/mail_content_removed.po:
CONTENT_TYPE_flipnote

el_GR/LC_MESSAGES/mail_content_restored.po:
CONTENT_TYPE_flipnote

el_GR/LC_MESSAGES/mail.po:
TITLE_SPINOFF

el_GR/LC_MESSAGES/mail_report_accepted.po:
CONTENT_TYPE_flipnote

el_GR/LC_MESSAGES/mail_report_rejected.po:
CONTENT_TYPE_flipnote

el_GR/LC_MESSAGES/mailSettings.po:
TYPE_PROMO_NAME

el_GR/LC_MESSAGES/menuHeaders.po:
MAIL

el_GR/LC_MESSAGES/musicMatch.po:
FLIPNOTE_COUNT

el_GR/LC_MESSAGES/reportContent.po:
CATEGORY_NAME_harassment
CATEGORY_NAME_rapid_flashing
CATEGORY_NAME_spam
FLIPNOTE

el_GR/LC_MESSAGES/search.po:
SEARCH_SHORT_KEY

el_GR/LC_MESSAGES/sudomemoPlus.po:
FLIPNOTE_AUDIO_ENHANCEMENT
FLIPNOTE_SMOOTHING
THEME_PUBLISHER_ACCESS

el_GR/LC_MESSAGES/theatre.po:
BTN_GO_TO_SETTINGS
CHANNEL_CAT_NAME_FANDOMS
CHANNEL_CAT_NAME_RESOURCES
CHANNEL_CAT_NAME_ROLEPLAYS
CHANNEL_CAT_NAME_WEEKLY_TOPIC
DATETIME_MONTH_DAY_ORDINAL_HOUR_MINUTE_SECOND_FORMAT
DATETIME_WEEKDAY_MONTH_DAY_ORDINAL_YEAR_FORMAT
DISCORD
EDIT_PAGE_PLUS_AUDIO_ENHANCEMENT
EDIT_PAGE_PLUS_SMOOTHING
FLIPNOTE
FLIPNOTE_ID
FLIPNOTES
FLIPNOTE_STUDIO_ID
FRONTPAGE_FLIPNOTE_SPOTLIGHT
FSID
HATENA_ID
HEADER_UPLOAD_TO_YOUTUBE
LINK_REQUIRED_BEFORE_UPLOAD
MUSICMATCH
NAVBAR_ITEM_ADMIN
NAVBAR_ITEM_DISCORD
NAVBAR_ITEM_EMAIL
NAVBAR_ITEM_FACEBOOK
NAVBAR_ITEM_INSTAGRAM
NAVBAR_ITEM_SUDOMEMO_ADMIN
NAVBAR_ITEM_TWITTER
NAVBAR_TOGGLE_NAVIGATION
NINTENDO_3DS
NINTENDO_DSI
RANK
SHARE
SUBMIT
SUDOMEMO
SUDOMEMO_PLUS
SUDOMEMO_THEATRE
TROPHY_CASE
VIEWPAGE_SPINOFFS
YOUTUBE
YOUTUBE_EXTRA_DESCRIPTION_TEXT
YOUTUBE_EXTRA_DESCRIPTION_TEXT_EXPLANATION
YOUTUBE_LOOP_COUNT
YOUTUBE_LOOP_COUNT_EXPLANATION
YOUTUBE_TAGS
YOUTUBE_TAGS_EXPLANATION
YOUTUBE_TAGS_HINT
YOUTUBE_VISIBILITY
YOUTUBE_VISIBILITY_PRIVATE
YOUTUBE_VISIBILITY_PUBLIC
YOUTUBE_VISIBILITY_UNLISTED

el_GR/LC_MESSAGES/themeShop.po:
PREVIEW

el_GR/LC_MESSAGES/tickets.po:
SUDOMEMO_CITIZENSHIP
SUDOMEMO_PLUS
TICKET_NAME_blue_dog_ticket
TICKET_NAME_colors_promo_ticket
TICKET_NAME_demo_ticket
TICKET_NAME_folding_reward_ticket
TICKET_NAME_golden_neko_ticket
TICKET_NAME_green_panda_ticket
TICKET_NAME_instagram_promo_ticket
TICKET_NAME_neighborhood_watch_ticket
TICKET_NAME_nitro_booster_ticket
TICKET_NAME_purple_bunny_ticket
TICKET_NAME_red_bird_ticket
TICKET_NAME_spookmaster_ticket
TICKET_NAME_twitter_promo_ticket

el_GR/LC_MESSAGES/trophies.po:
ACHIEVEMENT_EARNED
TROPHY_NAME_demo_tester
TROPHY_NAME_early_adopter
TROPHY_NAME_legacy_citizen
TROPHY_NAME_neighborhood_watch
TROPHY_NAME_nitro_booster
TROPHY_NAME_spookmaster

el_GR/LC_MESSAGES/unreadComments.po:
FLIPNOTE_ID

el_GR/LC_MESSAGES/youtube.po:
AUDIO_ENHANCEMENT
FLIPNOTE_SMOOTHING
PLUS_FEATURES
TAGS
YOUTUBE
YOUTUBE_ID
YOUTUBE_VISIBILITY_UNLISTED
```

If any of these should cannot translated into the target language then they should have their msgid's added to ignores file entries. You can see examples by looking into the `ignores` folder, and instructions can also be found in the README.md of this repository.

**Comment by sudofox** [comment]
```
# sudomemo-locales Problem Finder
Scans for problems as well as untranslated (or identical) strings

## el_GR

el_GR/LC_MESSAGES/chatrooms.po:
MODERATOR

```

**Comment by sudofox** [comment]
LGTM

**Pull request merged**
