### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by jojoispresent**
finally finished the missing german translation work

life's not been generous as of late so it took time to finally get to this, sorry about that

### CODE REVIEW

**Comment by sudofox** [comment]
```
./de_DE/LC_MESSAGES/login.po:41: end-of-line within string
./de_DE/LC_MESSAGES/login.po:41:5: syntax error
./de_DE/LC_MESSAGES/login.po:42: end-of-line within string
./de_DE/LC_MESSAGES/login.po:78: end-of-line within string
./de_DE/LC_MESSAGES/login.po:78:6: syntax error
./de_DE/LC_MESSAGES/login.po:79: end-of-line within string
msgfmt: found 6 fatal errors
```

Can you double-check these?

**Comment by jojoispresent** [comment]
should be all good now!

**Comment by sudofox** [comment]
Thanks!

I ran a check for untranslated strings and it found these ones:

```
## de_DE

de_DE/LC_MESSAGES/browseFlipnotes.po:
HEADER_FLIPNOTES
SUDOMEMO

de_DE/LC_MESSAGES/channelCategories.po:
GENRES

de_DE/LC_MESSAGES/channelDetails.po:
FLIPNOTES

de_DE/LC_MESSAGES/chatrooms.po:
MODERATOR

de_DE/LC_MESSAGES/creatorsRoom.po:
FAN_COUNT_FORMAT
FANS
RANKING
THEMETEST_OK
TICKET_SECTION
USER_THEME

de_DE/LC_MESSAGES/dailyStarReport.po:
STRING_SUDOMEMO

de_DE/LC_MESSAGES/detailsPage.po:
HEADER_DETAILS
HEADER_DOWNLOADS
HEADER_SONG
HEADER_UPLOAD_TO_YOUTUBE

de_DE/LC_MESSAGES/discordbot.po:
MUSICMATCH_MOVIE_COUNT_PLURAL
MUSICMATCH_MOVIE_COUNT_SINGULAR
USAGE_give_plus
USAGE_INTRO
USAGE_link
USAGE_musicmatch

de_DE/LC_MESSAGES/flipnoteComments.po:
HEADER_DETAILS
MODERATOR

de_DE/LC_MESSAGES/flipnoteOptions.po:
HEADER_STATUS
OPTION_NAME_SMOOTH

de_DE/LC_MESSAGES/followNotificationEmail.po:
GREETING_FORMAT
STATS_FLIPNOTES_FORMAT
STATS_FLIPNOTES_FORMAT_SINGULAR
STATS_FOLLOWERS_FORMAT_SINGULAR

de_DE/LC_MESSAGES/happyBirthdayEmail.po:
GREETING_FORMAT

de_DE/LC_MESSAGES/mail_content_removed.po:
CONTENT_TYPE_flipnote

de_DE/LC_MESSAGES/mail_content_restored.po:
CONTENT_TYPE_flipnote

de_DE/LC_MESSAGES/mail.po:
TITLE_INFO

de_DE/LC_MESSAGES/mail_report_accepted.po:
CONTENT_TYPE_flipnote

de_DE/LC_MESSAGES/mail_report_rejected.po:
CONTENT_TYPE_flipnote

de_DE/LC_MESSAGES/mailSettings.po:
MAIL_STATUS
TYPE_NEWS_NAME
TYPE_PROMO_NAME

de_DE/LC_MESSAGES/menuHeaders.po:
MAIL
NEWS

de_DE/LC_MESSAGES/musicMatch.po:
FLIPNOTE_COUNT
GENRE

de_DE/LC_MESSAGES/reportContent.po:
CATEGORY_NAME_spam
FLIPNOTE

de_DE/LC_MESSAGES/theatre.po:
CHANNEL_CAT_NAME_GENRES
DETAILS
DISCORD
DOWNLOADS
EDIT_PAGE_PLUS_SMOOTHING
FANS
FLIPNOTE
FLIPNOTES
FLIPNOTE_SETTINGS_UPLOAD_TO_YOUTUBE
FRONTPAGE_FLIPNOTE_SPOTLIGHT
FSID
GENRE
INFO
MODERATOR
MUSIC_LABEL
MUSICMATCH
NAVBAR_ITEM_ADMIN
NAVBAR_ITEM_CREDITS
NAVBAR_ITEM_DISCORD
NAVBAR_ITEM_EMAIL
NAVBAR_ITEM_FACEBOOK
NAVBAR_ITEM_FAQS
NAVBAR_ITEM_INSTAGRAM
NAVBAR_ITEM_SHOP
NAVBAR_ITEM_SUDOMEMO_ADMIN
NAVBAR_ITEM_TWITTER
NEWS
NINTENDO_3DS
NINTENDO_DSI
REGION
REGION_JAPAN
SONG
SUDOMEMO
SUDOMEMO_NEWS
SUDOMEMO_PLUS
SUDOMEMO_SHOP
SUDOMEMO_THEATRE
TICKETS
TOP
YOUTUBE
YOUTUBE_TAGS

de_DE/LC_MESSAGES/themeShop.po:
DETAILS
THEME

de_DE/LC_MESSAGES/tickets.po:
ACHIEVEMENT
SUDOMEMO_PLUS

de_DE/LC_MESSAGES/trophies.po:
TROPHY_NAME_nitro_booster

de_DE/LC_MESSAGES/youtube.po:
FLIPNOTE_SMOOTHING
PREVIEW_EXTRA_DESC
STATUS
TAGS
YOUTUBE
YOUTUBE_ID
```

To resolve these, please either update their translations or create ignore list entries for the relevant entries.

**Comment by jojoispresent** [comment]
ran by everything, and i can assure you that those work just as fine in german! they're all titles or short sentences (like **msgstr "Hey %s!"** in happyBirthdayEmail.po at line 10) that don't need translation to be comprehensible to german users

**Comment by sudofox** [comment]
> that don't need translation to be comprehensible to german users

Just for clarification, are the words the same in German as they are in English? Like, if someone only knew German and didn't know any English at all, would they make sense?

**Comment by jojoispresent** [comment]
the terms i did leave out were mostly names (like YouTube, Discord Flipnote), others are so generally known that it's hardly necessary
but if you want i can do something about the latter? just to be on the safe side

**Comment by sudofox** [comment]
>  but if you want i can do something about the latter? just to be on the safe side

Yeah, that'd be great!

**Comment by jojoispresent** [comment]
i'm now pretty sure that nothing was left out

**Comment by sudofox** [comment]
Cool. Here's the updated "no difference" list:

```
de_DE/LC_MESSAGES/browseFlipnotes.po:
HEADER_FLIPNOTES
SUDOMEMO

de_DE/LC_MESSAGES/channelCategories.po:
GENRES

de_DE/LC_MESSAGES/channelDetails.po:
FLIPNOTES

de_DE/LC_MESSAGES/chatrooms.po:
MODERATOR

de_DE/LC_MESSAGES/creatorsRoom.po:
FAN_COUNT_FORMAT
FANS
THEMETEST_OK
TICKET_SECTION

de_DE/LC_MESSAGES/dailyStarReport.po:
STRING_SUDOMEMO

de_DE/LC_MESSAGES/detailsPage.po:
HEADER_DETAILS
HEADER_SONG

de_DE/LC_MESSAGES/discordbot.po:
MUSICMATCH_MOVIE_COUNT_PLURAL
MUSICMATCH_MOVIE_COUNT_SINGULAR
USAGE_give_plus
USAGE_INTRO
USAGE_link
USAGE_musicmatch

de_DE/LC_MESSAGES/flipnoteComments.po:
HEADER_DETAILS
MODERATOR

de_DE/LC_MESSAGES/flipnoteOptions.po:
HEADER_STATUS

de_DE/LC_MESSAGES/followNotificationEmail.po:
GREETING_FORMAT
STATS_FLIPNOTES_FORMAT
STATS_FLIPNOTES_FORMAT_SINGULAR
STATS_FOLLOWERS_FORMAT_SINGULAR

de_DE/LC_MESSAGES/happyBirthdayEmail.po:
GREETING_FORMAT

de_DE/LC_MESSAGES/mail_content_removed.po:
CONTENT_TYPE_flipnote

de_DE/LC_MESSAGES/mail_content_restored.po:
CONTENT_TYPE_flipnote

de_DE/LC_MESSAGES/mail.po:
TITLE_INFO

de_DE/LC_MESSAGES/mail_report_accepted.po:
CONTENT_TYPE_flipnote

de_DE/LC_MESSAGES/mail_report_rejected.po:
CONTENT_TYPE_flipnote

de_DE/LC_MESSAGES/mailSettings.po:
MAIL_STATUS
TYPE_NEWS_NAME
TYPE_PROMO_NAME

de_DE/LC_MESSAGES/menuHeaders.po:
MAIL
NEWS

de_DE/LC_MESSAGES/musicMatch.po:
FLIPNOTE_COUNT
GENRE

de_DE/LC_MESSAGES/reportContent.po:
CATEGORY_NAME_spam
FLIPNOTE

de_DE/LC_MESSAGES/theatre.po:
CHANNEL_CAT_NAME_GENRES
DETAILS
DISCORD
FANS
FLIPNOTE
FLIPNOTES
FRONTPAGE_FLIPNOTE_SPOTLIGHT
FSID
GENRE
INFO
MODERATOR
MUSIC_LABEL
MUSICMATCH
NAVBAR_ITEM_ADMIN
NAVBAR_ITEM_CREDITS
NAVBAR_ITEM_DISCORD
NAVBAR_ITEM_EMAIL
NAVBAR_ITEM_FACEBOOK
NAVBAR_ITEM_FAQS
NAVBAR_ITEM_INSTAGRAM
NAVBAR_ITEM_SHOP
NAVBAR_ITEM_SUDOMEMO_ADMIN
NAVBAR_ITEM_TWITTER
NEWS
NINTENDO_3DS
NINTENDO_DSI
REGION
REGION_JAPAN
SONG
SUDOMEMO
SUDOMEMO_NEWS
SUDOMEMO_PLUS
SUDOMEMO_SHOP
SUDOMEMO_THEATRE
TICKETS
TOP
YOUTUBE
YOUTUBE_TAGS

de_DE/LC_MESSAGES/themeShop.po:
DETAILS

de_DE/LC_MESSAGES/tickets.po:
SUDOMEMO_PLUS

de_DE/LC_MESSAGES/trophies.po:
TROPHY_NAME_nitro_booster

de_DE/LC_MESSAGES/youtube.po:
STATUS
TAGS
YOUTUBE
YOUTUBE_ID
```

For each of these, please create a new ignores entry file. You can do it from GitHub itself like so:

Screenshot from 2020-12-28 18-03-15

(since the ignores/de_DE folder doesn't yet exist, just type `de_DE/<filename>.txt` for the first one and it'll autocreate it for you)

**Comment by jojoispresent** [comment]
image
it should look like this right?

**Comment by sudofox** [comment]
Yup, that's correct.

**Comment by sudofox** [comment]
Looking good! I think we're ready to merge it in.

What's your FSID btw?

**Pull request merged**
