### PR TITLE
[FR] updated

### PR DESCRIPTION
**Pull request by Furdox**
yeag

ArtiBlank

### CODE REVIEW

**Comment by Furdox** [comment]
idk why it keeps including previous unrelated commits, might just be github moment

**Comment by J0w03L** [comment]
did you run a `git fetch && git pull` before starting to work on the new translations?

**Comment by Furdox** [comment]
> did you run a `git fetch && git pull` before starting to work on the new translations?

did not do that because GitHub on web, I still need to properly set up Windows since Linux broke on me NeeloWAAA

**Comment by Furdox** [comment]
2024-05-21 22_51_27- FR  updated by Furdox · Pull Request #568 · Sudomemo_sudomemo-locales — Mozilla

**Comment by J0w03L** [comment]
wack, oh well. there's no merge conflicts so I think you're fine

**Comment by Furdox** [comment]
when will the meow be meowed

**Comment by Furdox** [comment]
thanks
ralsei_spin_roomba

**Pull request merged**
