### PR TITLE
es_ES Overhaul

### PR DESCRIPTION
**Pull request by meemo**
Mostly translations of untranslated strings and corrections.

### CODE REVIEW

**Comment by sudofox** [comment]
Can you fix the merge conflict?

**Comment by meemo** [comment]
Resolved

**Comment by sudofox** [comment]
```
[aburk@desktop sudomemo-locales]$ ./po2mo.sh > /dev/null 
./es_ES/LC_MESSAGES/discordbot.po:21: end-of-line within string
msgfmt: found 1 fatal error
./es_ES/LC_MESSAGES/theatre.po:897:9: syntax error
./es_ES/LC_MESSAGES/theatre.po:897: keyword "Est" unknown
./es_ES/LC_MESSAGES/theatre.po:898: end-of-line within string
msgfmt: found 3 fatal errors
```

**Comment by meemo** [comment]
Should be ready for merge now

**Pull request merged**
