### PR TITLE
French - Flipnote Friends

### PR DESCRIPTION
**Pull request by Jean20B**

### CODE REVIEW

**Comment by sudofox** [comment]
Is there any way you can make FLIPNOTE_FRIENDS_INFO shorter? If not, I'll fix it later to split it onto two lines (it takes some fiddling to get the alignment correct)

**Comment by Jean20B** [comment]
Yes I can, is it short enough?

**Comment by sudofox** [comment]
its probably fine
i'll merge it in the morning

**Comment by meemo** [comment]
Looks good, thanks!

**Pull request merged**
