### PR TITLE
Last update for a while (ZA)

### PR DESCRIPTION
**Pull request by KingMayro**
Final update to ZA until we get new text strings. If anything could be added, please tell me.

### CODE REVIEW

**Comment by sudofox** [comment]
I did this from my phone so I might be looking at it weird but one of the msgids seems off?

Stylistic feedback:

I would prefer that Sudomemo not be referred to as Sudomeme

Flippy-wippies feels a bit too much like baby talk than lolspeak tbh

Possible alternatives

Flipknot
Floopas
Flimp note
idk

**Comment by KingMayro** [comment]
Fixed I think.

**Comment by sudofox** [comment]
pls shorten NO_BLANK_COMMENTS_ALLOWED, it won't fit as this is rendered in a way that it won't wrap to a new line (will just run off the screen)

**Comment by sudofox** [comment]
i woulda gone with the second but works for me haha

**Comment by KingMayro** [comment]
Epic

**Comment by sudofox** [comment]
squashing and merging

i think the reason why it shows all the old commits is that https://stackoverflow.com/a/55251324/1091442

**Pull request merged**
