### PR TITLE
 added greek

### PR DESCRIPTION
**Pull request by igantzia**
I just translated stuff to greek for sudomemo.
Pls accept allmighty sudofox :)
You should accept because youre cool and cool people would accept it

### CODE REVIEW

**Comment by jaames** [comment]
looks good to me!

**Comment by igantzia** [comment]
whhop whoopppp!! :D

**Comment by sudofox** [comment]
**_Ευχαριστώ!_**

Merging PR into master, will test a bit later.

**Comment by igantzia** [comment]
Παρακαλώ ^_^

**Pull request merged**
